function main () {
wall → set background(colors → random → darken(0.4))
wall → show back button(false)
data → board := media → create landscape board(1920, 1080)
data → board → set background(colors → black)
play_button := data → board → create picture(art → playbutton)
play_button → set pos(data → board → width / 2, data → board → height / 2 - 100)
play_button → set z index(5)
code → playButton_events(play_button)
quit_button := data → board → create picture(art → quitbutton)
quit_button → set pos(data → board → width / 2, data → board → height / 2 + 100)
quit_button → set z index(5)
code → quitButton_events(quit_button)
code → displayReadyText(false)
data → board → post to wal
